import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './component/layout/header/pages';
import StyledComponentsRegistry from './lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'uglymews',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <link rel="icon" href="/umLogo.png" />
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <Header />
                    {children}
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
